//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Lenguajes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapaPresentacion.Lenguajes.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion de clases.
        /// </summary>
        internal static string administraciónDeClasesToolStripMenuItem {
            get {
                return ResourceManager.GetString("administraciónDeClasesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion de clientes.
        /// </summary>
        internal static string administraciónDeClientesToolStripMenuItem {
            get {
                return ResourceManager.GetString("administraciónDeClientesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion de productos.
        /// </summary>
        internal static string administraciónDeProductosToolStripMenuItem {
            get {
                return ResourceManager.GetString("administraciónDeProductosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de turnos.
        /// </summary>
        internal static string administraciónDeTurnosToolStripMenuItem {
            get {
                return ResourceManager.GetString("administraciónDeTurnosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestion de empleados y usuarios.
        /// </summary>
        internal static string administraciónDeUsuariosToolStripMenuItem {
            get {
                return ResourceManager.GetString("administraciónDeUsuariosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion de Clientes.
        /// </summary>
        internal static string btnAdmClientes {
            get {
                return ResourceManager.GetString("btnAdmClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desloguear.
        /// </summary>
        internal static string btnDesloguear {
            get {
                return ResourceManager.GetString("btnDesloguear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestion de abono.
        /// </summary>
        internal static string btnGestionAbono {
            get {
                return ResourceManager.GetString("btnGestionAbono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestion de clases.
        /// </summary>
        internal static string btnGestionClases {
            get {
                return ResourceManager.GetString("btnGestionClases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestion de turnos.
        /// </summary>
        internal static string btnGestionTurnos {
            get {
                return ResourceManager.GetString("btnGestionTurnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string btnIngreso {
            get {
                return ResourceManager.GetString("btnIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loguear.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reposicion de productos.
        /// </summary>
        internal static string btnReposProducto {
            get {
                return ResourceManager.GetString("btnReposProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Venta de productos.
        /// </summary>
        internal static string btnVentaProductos {
            get {
                return ResourceManager.GetString("btnVentaProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clases.
        /// </summary>
        internal static string clasesToolStripMenuItem {
            get {
                return ResourceManager.GetString("clasesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string clientesToolStripMenuItem {
            get {
                return ResourceManager.GetString("clientesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial.
        /// </summary>
        internal static string clientesToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("clientesToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string clientesToolStripMenuItem2 {
            get {
                return ResourceManager.GetString("clientesToolStripMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de Ingreso.
        /// </summary>
        internal static string controlDeIngresoToolStripMenuItem {
            get {
                return ResourceManager.GetString("controlDeIngresoToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestion de abono.
        /// </summary>
        internal static string gestiónDeAbonoToolStripMenuItem {
            get {
                return ResourceManager.GetString("gestiónDeAbonoToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestion de permisos.
        /// </summary>
        internal static string gestiónDePermisosToolStripMenuItem {
            get {
                return ResourceManager.GetString("gestiónDePermisosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso.
        /// </summary>
        internal static string ingresoToolStripMenuItem {
            get {
                return ResourceManager.GetString("ingresoToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDClient.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de ingreso.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Logueado.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        internal static string productosToolStripMenuItem {
            get {
                return ResourceManager.GetString("productosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        internal static string reportesToolStripMenuItem {
            get {
                return ResourceManager.GetString("reportesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        internal static string reportesToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("reportesToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turnos.
        /// </summary>
        internal static string turnosToolStripMenuItem {
            get {
                return ResourceManager.GetString("turnosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar Nomina.
        /// </summary>
        internal static string usuariosToolStripMenuItem {
            get {
                return ResourceManager.GetString("usuariosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Totales.
        /// </summary>
        internal static string usuariosToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("usuariosToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string usuariosToolStripMenuItem2 {
            get {
                return ResourceManager.GetString("usuariosToolStripMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string usuariosToolStripMenuItem3 {
            get {
                return ResourceManager.GetString("usuariosToolStripMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        internal static string ventasToolStripMenuItem {
            get {
                return ResourceManager.GetString("ventasToolStripMenuItem", resourceCulture);
            }
        }
    }
}
